# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++ bash curl

# Enable pnpm via Corepack
RUN corepack enable && corepack prepare pnpm@8.15.7 --activate

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy source and build
COPY . .
RUN pnpm build

# Expose port
EXPOSE 3000

# Start the Next.js MCP server, listening on $PORT
CMD ["pnpm", "start"]
